name: Mathias Koerth
description: Full Stack Developer Portfolio - Showcase of my skills and projects
keywords: [full stack developer, web development, front-end, back-end, JavaScript, React.js, Node.js, portfolio]